name: automerge 

on: 
  pull_request:
    branches:
      - master

jobs: 
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for status checks
        id: tests 
        uses: WyriHaximus/github-action-wait-for-status@0.1.0
        with:
          ignoreActions: automerge
          checkInterval: 60
      - name: automerge
        if: steps.tests.outputs.status == 'success'
        uses: pascalgn/automerge-action@v0.8.3
        env: 
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          MERGE_LABELS: "automerge"
          MERGE_REMOVE_LABELS: "automerge"
          MERGE_RETRIES: 1
      - name: Failure message
        if: steps.tests.outputs.status != 'success'
        run: echo 'failure'