name: automerge 

on: 
  pull_request:
    branches:
      - master

jobs: 
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for status checks
        # id: tests 
        # uses: fountainhead/action-wait-for-check@v1.0.0
        # with: 

        uses: jitterbit/await-check-suites@v1
        with: 
          timeoutSeconds: 120
          intervalSeconds: 10

      # - name: Wait for status checks
      #   id: tests 
      #   uses: WyriHaximus/github-action-wait-for-status@0.1.0
      #   with:
      #     checkInterval: 60
      #     ignoreActions: automerge
      - name: Merge pull request 
        # if: steps.tests.outputs.status == 'success'
        if: '!failure()'
        uses: pascalgn/automerge-action@v0.8.3
        env: 
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          MERGE_LABELS: "automerge"
          MERGE_REMOVE_LABELS: "automerge"
          MERGE_RETRIES: 1
      - name: Send failure message
        # if: steps.tests.outputs.status == 'failure'
        if: failure()
        run: echo 'failure'