name: automerge 

on: 
  pull_request:
    branches:
      - master
  check_suite:
    types: [completed]

jobs: 
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: pascalgn/automerge-action@v0.8.3
        env: 
          # GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_LABELS: "automerge"
          MERGE_REMOVE_LABELS: "automerge"
