name: tests

on: [pull_request]

jobs:
  tests:
    if: github.base_ref == 'master'
    runs-on: ubuntu-latest
    steps:
    - name: Script
      run: sleep 15s 
    - run: echo "${{ github.base_ref }}"