name: tests

on: [pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Set environment variable
        run: |
          if [[ ${{ github.ref }} == "refs/heads/release" ]]; then
            echo '::set-env name=environment::staging'
          else
            echo '::set-env name=environment::prod'
          fi
          echo "${{ jobs.tests.env.environment }}"
      - uses: Ilshidur/action-slack@efb86f
        env: 
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CUSTOM_PAYLOAD: '{
            "blocks":[
              {
                "type":"section",
                "text": 
                  { 
                    "type":"mrkdwn",
                    "text":":x:  Khepri $ENV deploy puppeteer suite failure @aps-oncall  :x:"
                  }
              },
              {
                "type":"context",
                "elements":[{
                  "type":"mrkdwn",
                  "text":"Check failing tests <https://github.com/chanzuckerberg/khepri/commit/${{ github.sha }}/checks|here>."
                }]
              }
            ]
          }'